CRITICAL - 2022-02-28 20:37:46 --> Class "Config\Auth" not found
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(264): include_once()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Auth')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Auth')
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Config\Factories.php(136): class_exists('Config\\Auth')
#5 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Config\Factories.php(106): CodeIgniter\Config\Factories::locateClass(Array, 'Auth')
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Common.php(198): CodeIgniter\Config\Factories::__callStatic('config', Array)
#7 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(29): config('Auth')
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(809): Myth\Auth\Controllers\AuthController->__construct()
#9 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#10 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-02-28 20:52:25 --> Cannot declare class App\Controllers\AuthController, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-28 20:52:59 --> Cannot declare class App\Controllers\AuthController, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-28 20:53:25 --> Cannot declare class App\Controllers\AuthController, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-28 20:53:27 --> Cannot declare class App\Controllers\AuthController, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-02-28 20:57:38 --> Call to undefined function link_tag()
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#4 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(429): view('App\\Views\\Auth\\...', Array)
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(57): Myth\Auth\Controllers\AuthController->_render('App\\Views\\Auth\\...', Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 20:59:17 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 20:59:40 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 21:00:02 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 21:00:28 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 21:00:45 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 21:01:42 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 21:02:30 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 21:02:56 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 21:03:47 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 21:04:43 --> Myth\Auth\Authentication\Passwords\CompositionValidator::check(): Argument #2 ($user) must be of type ?CodeIgniter\Entity, Myth\Auth\Entities\User given, called in C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php on line 55
#0 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\CompositionValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Authentication\Passwords\ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('BzkR5YzXmfJppz6', Object(Myth\Auth\Entities\User))
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(291): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('BzkR5YzXmfJppz6', NULL)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'BzkR5YzXmfJppz6', Array, Array)
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(172): CodeIgniter\Controller->validate(Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 22:39:13 --> Class "Myth\Auth\Controllers\Controller" not found
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(264): include_once()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Myth\\Auth\\Contr...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Myth\\Auth\\Contr...')
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(797): class_exists('\\Myth\\Auth\\Cont...', true)
#5 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(406): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-28 22:39:21 --> Class "App\Controllers\Controller" not found
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(264): include_once()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Myth\\Auth\\Contr...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Myth\\Auth\\Contr...')
#4 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(797): class_exists('\\Myth\\Auth\\Cont...', true)
#5 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(406): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-28 22:39:38 --> Call to undefined function link_tag()
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#4 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(429): view('App\\Views\\Auth\\...', Array)
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(57): Myth\Auth\Controllers\AuthController->_render('App\\Views\\Auth\\...', Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 22:42:19 --> Call to undefined function link_tag()
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#4 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(429): view('App\\Views\\Auth\\...', Array)
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(57): Myth\Auth\Controllers\AuthController->_render('App\\Views\\Auth\\...', Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 22:43:32 --> Call to undefined function link_tag()
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#4 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(429): view('App\\Views\\Auth\\...', Array)
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(57): Myth\Auth\Controllers\AuthController->_render('App\\Views\\Auth\\...', Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 22:43:35 --> Call to undefined function link_tag()
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#4 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(429): view('App\\Views\\Auth\\...', Array)
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(57): Myth\Auth\Controllers\AuthController->_render('App\\Views\\Auth\\...', Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 22:43:40 --> Call to undefined function link_tag()
#0 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('App\\Views\\Auth\\...', Array, true)
#4 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(429): view('App\\Views\\Auth\\...', Array)
#5 C:\xampp\htdocs\sgp\main\vendor\myth\auth\src\Controllers\AuthController.php(57): Myth\Auth\Controllers\AuthController->_render('App\\Views\\Auth\\...', Array)
#6 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#7 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-28 22:45:55 --> Myth\Auth\Authentication\Activators\EmailActivator::send(): Argument #1 ($user) must be of type ?Myth\Auth\Entities\User, App\Entities\User given, called in C:\xampp\htdocs\sgp\main\app\Controllers\AuthController.php on line 189
#0 C:\xampp\htdocs\sgp\main\app\Controllers\AuthController.php(189): Myth\Auth\Authentication\Activators\EmailActivator->send(Object(App\Entities\User))
#1 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\AuthController->attemptRegister()
#2 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\sgp\main\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\sgp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
